# Generated by Django 3.2.19 on 2023-07-08 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0002_auto_20230708_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 12, 10, 52, 327680, tzinfo=utc)),
        ),
    ]
