# Generated by Django 3.2.19 on 2023-07-08 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0003_auto_20230708_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='related_polls', to='PollApp.Choice'),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 12, 21, 25, 172965, tzinfo=utc)),
        ),
    ]
