# Generated by Django 3.2.19 on 2023-07-08 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0004_auto_20230708_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 13, 6, 58, 614943, tzinfo=utc)),
        ),
    ]
